/*
 * IRremote.h — NEC infrared send/receive for the Ai-WB2-12F (BL602).
 *
 * Send (IRsend): the 38 kHz carrier is generated by a BL602 PWM channel
 * (pin must be PWM-capable, i.e. not the non-PWM GPIO 11) and gated per NEC
 * pulse with bl_pwm_set_duty(). The carrier runs in hardware, so interrupts
 * may stay enabled during transmission.
 *
 * Receive (IRrecv): a TSOP demodulator pulls its output LOW while 38 kHz is
 * present. attachInterrupt(pin, CHANGE) records the time of every edge into
 * a small ring of durations; decode() then walks the ring looking for the
 * NEC header and 32 data bits. Inter-frame gaps > 50 ms are dropped.
 *
 * NEC timing (nominal): 9 ms mark, 4.5 ms space, then 32 bits LSB-first —
 * each bit is a 562 us mark followed by 562 us (0) or 1687 us (1) of space.
 */
#ifndef IRremote_h
#define IRremote_h

#include <Arduino.h>

/* Durations recorded by the receiver (16-bit, > 50 ms gaps are skipped). */
#define IR_RECV_BUFSIZE 128
#define IR_IDLE_MAX_US  50000UL

typedef struct {
    uint32_t value;  /* decoded 32-bit NEC data (0 on repeat frame) */
    bool     repeat; /* true if this was a NEC repeat frame */
} IRResults;

/* ---------------- transmit ---------------- */

class IRsend
{
public:
    IRsend(uint8_t pin) : _pin(pin), _ch(pin % 5), _freq(38000) {}

    void begin(void);                 /* configure the PWM carrier */
    void sendNEC(uint32_t data, uint8_t nbits = 32);
    void sendRaw(const uint16_t *buf, uint16_t len,
                 uint16_t hz = 38000); /* alternating mark/space, us */

private:
    uint8_t  _pin;
    uint8_t  _ch;   /* BL602 PWM channel = GPIO % 5 */
    uint32_t _freq;

    void _carrier(bool on);          /* duty 33% while on, 0 while off */
    void _mark(uint32_t us);
    void _space(uint32_t us);
};

/* ---------------- receive ---------------- */

class IRrecv
{
public:
    IRrecv(uint8_t pin) : _pin(pin) {}

    void enableIRIn(void);
    void disableIRIn(void);
    void resume(void);                 /* flush buffered durations */
    uint8_t available(void) const;

    /* Non-blocking. Returns true and fills *results when a complete frame
     * has been buffered and consumed. Call resume() between frames. */
    bool decode(IRResults *results);

private:
    uint8_t _pin;
    static IRrecv *s_self;             /* the ISR needs an instance */
    static void isr(void);
};

#endif /* IRremote_h */
