name=AiWB2
version=0.1.0
author=Ai-Thinker
maintainer=Ai-Thinker <support@ai-thinker.com>
sentence=Ai-Thinker Ai-WB2-12F (BL602) core example sketches
paragraph=
category=Other
url=
architectures=wb2
